spring.application.name=Journal
# spring.mongodb.uri=mongodb+srv://shivanandhanj22cse:nanzu_05@cluster0.qcf0s.mongodb.net/?appName=Cluster0

spring.mongodb.uri=mongodb+srv://shivanandhanj22cse:li1EbhLAWNVp7lGD@cluster0.qcf0s.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.auto-index-creation=true